### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by qingsongya** [25H/Maya#1]
1、多次点击maya的启动程序，可以开启多个窗口，希望优化一下，直接弹出主界面即可，不用打开多个窗口，这是多开了？
2、分类中的项目无法移动其它分类，希望可以支持一下，最好也支持拖动图标移动分类。
3、能否搞个分类下增加标签功能，也就是二级分类。

**Comment by 25H** [comment]
软件多开问题会在下个版本中修复，另外没有做二级分类的打算

**Comment by 25H** [comment]
软件多开问题会在下个版本中修复，另外没有做二级分类的打算

> 1，多次点击maya的启动程序，可以打开多个窗口，希望优化一下，直接拖动主界面即可，不用打开多个窗口，这是多开了？
> 2，分类中的项目无法移动其他分类，希望可以支持一下，最好也支持初始化图标移动分类
> 。3，能否搞个分类下增加标签功能，也就是二级分类。

软件多开问题会在下个版本中修复，另外没有做二级分类的打算

**Comment by 25H** [comment]
> 1、多次点击maya的启动程序，可以开启多个窗口，希望优化一下，直接弹出主界面即可，不用打开多个窗口，这是多开了？
> 2、分类中的项目无法移动其它分类，希望可以支持一下，最好也支持拖动图标移动分类。
> 3、能否搞个分类下增加标签功能，也就是二级分类。

软件多开问题会在下个版本中修复，另外没有做二级分类的打算
