### ISSUE TITLE
建议： 分类多标签能够设置上下左右

### ISSUE THREAD

**Issue by tagaga** [25H/Maya#10]
目前多标签页是在最左边，建议能否让用户设置位置，可以位于上面，或者下面，或者右边，可以参考一下hurryrun；从操作易用性的角度，通常鼠标点击系统图标都是从右下角移动的，如果标签在界面的右边鼠标移动距离是最小的，操作体验最好

**Comment by 25H** [comment]
这功能暂不考虑开发，后期需求较大可能会考虑开发😊

**Comment by tagaga** [comment]
这么能够提高软件易用性的建议都不采纳，唉，只能继续使用hurryrun了，一个10几年前的软件
