### ISSUE TITLE
分类组里多个图标右键失效

### ISSUE THREAD

**Issue by xivi1839** [25H/Maya#103]
如果一个分类组里有21个图标，点击这块右边空白区域，右键失效，不显示菜单，你们测试看看，
![_20211718041720](https://user-images.githubusercontent.com/24610024/111532670-e287cd80-87a0-11eb-898f-056de23e7cba.png)

**Comment by 25H** [comment]
21个项目右键菜单没问题啊
________________________________
发件人: xivi1839 ***@***.***>
发送时间: 2021年3月18日 上午 04:13
收件人: 25H/Maya ***@***.***>
抄送: Subscribed ***@***.***>
主题: [25H/Maya] 分类组里多个图标右键失效 (#103)


如果一个分类组里有21个图标，右键失效，不显示菜单，你们测试看看

―

**Comment by xivi1839** [comment]
就是一行里一个图标，右边空白区域点击右键不显示菜单

**Comment by 25H** [comment]
发下`jdb.json`我测试下

**Comment by xivi1839** [comment]
这里https://zoe190.lanzous.com/iBOF9n65cij
