### ISSUE TITLE
设置|动作|显示与隐藏 快捷键设置 和 显示时跟随鼠标位置  针对 多屏只能在主屏 显示与隐藏

### ISSUE THREAD

**Issue by MRkuan** [25H/Maya#115]
如题

实测 ROLAN没有这个问题，可以跟着鼠标走到其它附屏

![image](https://user-images.githubusercontent.com/22144017/117625764-f2240100-b1a8-11eb-8d6a-50ddb8cdb096.png)

**Comment by MRkuan** [comment]
> 这功能只会在主屏显示？

是的，我已经和ROLAN 对比过了，还有 一个槽点， 这个设置界面不跟着主题走，我现在是黑色主题，但是 设置界面还是白色的

**Comment by 25H** [comment]
这毛病有空我修一下，至于设置那算了懒得写🤣

**Comment by MRkuan** [comment]
> 这毛病有空我修一下，至于设置那算了懒得写

可以指导下设置界面怎么改和主界面主题一致，可以让用户自己来？强迫症人无法忍受 <_<

**Comment by 25H** [comment]
设置界面目前没有开放任何接口，而且设置那里弄好后半年都不一定能打开一次🤦‍♂️
