### ISSUE TITLE
非常好的软件，标星的同时提点小建议和Bug

### ISSUE THREAD

**Issue by wogexiatian** [25H/Maya#12]
个人日常生活工作比较依赖这种快捷启动软件，目前类似软件挺多，但是这样美观小巧的没几个。Rolan以前很棒，但是Rolan2基本停止维护，3做得过于臃肿80%的功能我都不需要或者有更好的软件可以替代。Lily外观无法自定义且卡死Bug一直不修，能发现Maya真的让我非常高兴。在此从我的个人需求角度出发提些小建议和Bug，希望它能更好用。
1.目前软件在我的笔记本上存在配置保存失败的问题，盲测可能是由于软件目录位于C盘的原因（我只有C盘），以管理员身份运行后可以正常保存配置，但是无法向启动板内添加文件夹和软件，这就很讨厌，直接导致我无法将其作为我的主力快捷启动软件；
2.目前最新的1.0.6版本内，原本内置的各种皮肤都消失了，希望之后的版本能加回来或者增加一些自定义皮肤的功能；
3.希望以后的版本透明度设置能增加高斯模糊的选项，和系统更加契合；
4.希望以后能调节启动板侧边栏的宽度

**Comment by 25H** [comment]
无法保存可以检查下权限
1.0.6没内置皮肤时因为忘记了。。
透明/模糊 可以在 /skin/***.less 加入相关css代码实现 (参考：https://blog.arae.cc/post/25831.html)
侧边栏宽度可以通过修改 /skin/***.less 中的 layoutLeftWidth 实现

😊
