### ISSUE TITLE
关于快捷搜索自定义图标

### ISSUE THREAD

**Issue by toyqiu** [25H/Maya#128]
请教快捷搜索是否能自定义图标？要如何实现？

**Comment by 25H** [comment]
快捷搜索自定义图标？？？？？
啥意思？

**Comment by toyqiu** [comment]
> 快捷搜索自定义图标？？？？？
> 啥意思？

不好意思没看到帮助
不过看了之后还是不太明白，icon参数要怎么添加

clips|搜索|true|so1|ico|icon路径 https://xxxx.cc/search?q=%s
这样可以吗
