### ISSUE TITLE
无法正常显示 edge/chrome 所创建的快捷方式的图标

### ISSUE THREAD

**Issue by hunmer** [25H/Maya#13]
如题,将带有网站图标的快捷方式拖放进去后只能显示浏览器的图标,希望可以兼容一下.

**Comment by 25H** [comment]
会尽快增加这项功能的👌

**Comment by 25H** [comment]
edge/chrome 创建的时lnk而分url，lnk图标获取方式为提取目标文件图标而非快捷方式图标，可以尝试自行建立url类型快捷方式拖入maya
