### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by MrFour4444** [25H/Maya#131]
[
![0S3P}S02TSYAQ5~YRL@OGK](https://user-images.githubusercontent.com/62591745/124857556-16e8f900-dfdf-11eb-8e1e-18d3c3e52f4e.png)
](url)图标会变成这个样子，试过重建图标预缓了，没用。PS的图标也会这样。还有没有其他的我不知道，希望可以尽快修复

**Comment by 25H** [comment]
右键编辑，截份图我看看

**Comment by MrFour4444** [comment]
[
![8O67FX@EE}P%1P8 3CSLS 9](https://user-images.githubusercontent.com/62591745/125019969-8677ea80-e0aa-11eb-92a4-10ae9348be65.png)
](url)

**Comment by MrFour4444** [comment]
不能解决吗？

**Comment by 25H** [comment]
复现不出，找不到问题🤦‍♂️
