### ISSUE TITLE
命名输入中文显示为？？？

### ISSUE THREAD

**Issue by Drawlone** [25H/Maya#132]
类似#99，但他的解决方法并不起作用，我是在win11上出现的问题，将微信和QQ移入之后，名称也变成乱码，请问如何解决
![image](https://user-images.githubusercontent.com/31383809/126040015-8846f1a3-2388-40cc-8497-044335c56a09.png)

**Comment by Drawlone** [comment]
另外，我在该系统中使用了Unciode选项，我不确定是否是这里影响到中文输入
![image](https://user-images.githubusercontent.com/31383809/126040131-50d336c4-dd18-4a83-a863-6fb5ca07d397.png)

**Comment by 25H** [comment]
win11上不确定，我有空测试下

**Comment by Drawlone** [comment]
当我取消Unicode这个选项后，问题解决了，输入正常，问题的确出在这里
![image](https://user-images.githubusercontent.com/31383809/128362300-98c6a68a-f5f6-42f2-bc1b-fa98af6d4c2c.png)
