### ISSUE TITLE
连英雄联盟的图标的也会变成这样

### ISSUE THREAD

**Issue by MrFour4444** [25H/Maya#134]
![HVRCFU NU$4_E$TBZ}VD7](https://user-images.githubusercontent.com/62591745/126890352-c3e2cd5f-0ae3-4d54-8968-55a12330fe9e.png)

**Comment by 25H** [comment]
那个文件发过来，我测试下

**Comment by MrFour4444** [comment]
什么文件？

**Comment by MrFour4444** [comment]
而且怎么升级新版本？重新下载？

**Comment by 25H** [comment]
> 而且怎么升级新版本？重新下载？

下新版覆盖旧版
