### ISSUE TITLE
高分辨率显示异常

### ISSUE THREAD

**Issue by xun-mi-git** [25H/Maya#137]
![寻觅_20210415010450](https://user-images.githubusercontent.com/43723838/129454883-fbe587c3-d2b4-4491-b3ae-f8bac1bfd1d3.png)
我的笔记本是4k分辨率屏幕,显示软件界面异常字体有的特别小,有的特别大,使用兼容模式后,界面直接无法显示。

**Comment by 25H** [comment]
目前最新版是1.2.4，建议升下级，
