### ISSUE TITLE
快捷键能否添加win键的支持呢？

### ISSUE THREAD

**Issue by LanbingIce** [25H/Maya#146]
之前用Rolan快捷键一直都是win+alt+space，换成Maye发现快捷键不能设win键，能否添加一下支持呢

**Comment by 25H** [comment]
![Screenshot_2021-09-13_17-17-18](https://user-images.githubusercontent.com/36186834/133058185-79f3ea90-63ab-401d-96f7-e499d9e1f3a6.png)
可以用啊

**Comment by LanbingIce** [comment]
我还是没法直接设置，但是我通过修改配置文件的方式设置了，现在能用了
