### ISSUE TITLE
修改列表显示类型和项目名显示行数，似乎不生效，重启过

### ISSUE THREAD

**Issue by Dustin-Hayes-Hong** [25H/Maya#148]
![image](https://user-images.githubusercontent.com/78560143/136005580-5266c5e5-7cc0-4019-8441-77aa21ad463c.png)

**Comment by 25H** [comment]
升到1.2.6

**Comment by Dustin-Hayes-Hong** [comment]
> 升到1.2.6

已经是1.2.6了

**Comment by 25H** [comment]
分类右键高于全局，如果设置过且想用全局则需要自己到json里删除

**Comment by Dustin-Hayes-Hong** [comment]
> 分类右键高于全局，如果设置过且想用全局则需要自己到json里删除

原来可以右键分类调整，是我疏忽了
