### ISSUE TITLE
希望改进tips提示

### ISSUE THREAD

**Issue by zhouhuajdsh** [25H/Maya#15]
现在显示的进程优先级对用户来说可能不是很需要

建议显示有用的几项
项目名称：
项目链接：
启动参数：
项目备注：

如图示例
![Snipaste_2020-12-05_17-10-07](https://user-images.githubusercontent.com/29763911/101238799-9b0f9100-371d-11eb-9852-6d656fcd1bb5.jpg)

**Comment by 25H** [comment]
感谢提供建议。
