### ISSUE TITLE
请问：为啥用着用着软件就消失(卸载)了

### ISSUE THREAD

**Issue by Hz-Cool** [25H/Maya#158]
用着用着软件就消失(卸载)了
这应该是第二次出现这个问题了
不明所以

[![oOc5ut.png](https://s4.ax1x.com/2021/12/13/oOc5ut.png)](https://imgtu.com/i/oOc5ut)

**Comment by Hz-Cool** [comment]
用着用着 = 1~3个月

**Comment by 25H** [comment]
大概率被杀软干掉了

**Comment by Losfinding1** [comment]
昨天报毒后就发现软件不见了
