### ISSUE TITLE
搜索功能经常会卡顿

### ISSUE THREAD

**Issue by Pandolar** [25H/Maya#160]
搜索功能经常会卡顿
进入软件直接输入会有延迟
请问这个问题可以解决吗

**Comment by 25H** [comment]
输入延迟可能是输入法的原因，换个试试看

**Comment by Pandolar** [comment]
![bandicam 2021-12-27 09-14-20-814](https://user-images.githubusercontent.com/54896726/147425107-4916ec34-eb43-4b22-b601-b273dc96fb2a.gif)
![bandicam 2021-12-27 09-16-13-594](https://user-images.githubusercontent.com/54896726/147425109-2eb8e53c-bdf3-4a3d-b8d9-63edd108f256.gif)

关闭输入法后使用搜索功能仍然有0.5s左右的延迟

**Comment by 25H** [comment]
你那里大概有多少项目，我测试下看看

**Comment by Pandolar** [comment]
[Maye.zip](https://github.com/25H/Maya/files/7778757/Maye.zip)
Maye是最新的  系统版本Windows 10 专业工作站版21H1  19043.1055

**Comment by 25H** [comment]
项目太多，前端及时搜索性能较差，可以尝试关掉"搜索范围"与"匹配条件"里面的选项

**Comment by Pandolar** [comment]
好的, 关闭后好一些了
