### ISSUE TITLE
程序标题栏默认名称 -Admin 是怎么回事儿，能否去掉呢

### ISSUE THREAD

**Issue by PrinceFPF** [25H/Maya#161]
如下这个位置的文字并不能通过设置去掉，有什么办法吗
![图片](https://user-images.githubusercontent.com/11377700/147385540-0067a403-3551-41cc-9f35-edb95ed8c60b.png)

**Comment by 25H** [comment]
表示当前为管理员权限运行，后续在maye里面打开的程序都会继承这个权限，不想显示可以在设置里关掉

**Comment by PrinceFPF** [comment]
感谢，按照你的提示，找到了。
![图片](https://user-images.githubusercontent.com/11377700/147388116-acdde6c6-2cce-4128-bcbe-aeb2b28cb15b.png)
