### ISSUE TITLE
更新1.2.7，重建图标缓存后，部分图标编的特别小

### ISSUE THREAD

**Issue by LeslieSong** [25H/Maya#162]
如图，右键重建图标缓存也没有用，之前显示都正常
![image](https://user-images.githubusercontent.com/10683931/147425386-72cccfc8-c9cf-4f09-b529-6fbbf5ec0085.png)

**Comment by lendlice13** [comment]
我也是这样...手贱运行了重建缓存。。。

**Comment by 25H** [comment]
出现问题的文件发出来我测试下

**Comment by LeslieSong** [comment]
> 

[小图标.zip](https://github.com/25H/Maya/files/7778673/default.zip)


> 出现问题的文件发出来我测试下

**Comment by 25H** [comment]
> > 
> 
> [小图标.zip](https://github.com/25H/Maya/files/7778673/default.zip)
> 
> > 出现问题的文件发出来我测试下

我这里测试没事啊，试试这个
```
    - 删除或清空以下文件生效
        - /cache/icon/
        - /cache/MemoryCache.dat
        - /cache/MemoryCacheKey.json
```

**Comment by LeslieSong** [comment]
> 

安装的时候就这么搞的，不过只有第一个文件夹，没有dat和json文件
