### ISSUE TITLE
64wei de you ma

### ISSUE THREAD

**Issue by dianso** [25H/Maya#163]
64wei de you ma

**Comment by 25H** [comment]
？？？？？

**Comment by mx4994** [comment]
帮忙翻译：64位的有嘛？
帮忙回复：可以有，但没必要。

**Comment by 25H** [comment]
这个是64位的
https://blog.arae.cc/post/25842.html

**Comment by mx4994** [comment]
> 这个是64位的 https://blog.arae.cc/post/25842.html

不是还没发布么。
