### ISSUE TITLE
部分图标显示过小；是否可以增加图片背景

### ISSUE THREAD

**Issue by 236507** [25H/Maya#165]
![image](https://user-images.githubusercontent.com/93651002/147520912-c300ed23-c938-47ec-8d00-c892eb76ac60.png)
部分图标显示过小，其他类似软件显示正常的，下图
![image](https://user-images.githubusercontent.com/93651002/147520981-ce05912f-29a3-496a-969a-722933824eb6.png)

**Comment by 25H** [comment]
更新到1.2.8并
```
删除或清空以下文件生效
/cache/icon/
/cache/MemoryCache.dat
/cache/MemoryCacheKey.json
```

**Comment by 236507** [comment]
解决。谢谢
是否可以增加图片背景

**Comment by 25H** [comment]
https://blog.arae.cc/post/25831.html

**Comment by 25H** [comment]
> 否可以增加图片背景

https://blog.arae.cc/post/25831.html
