### ISSUE TITLE
bug 设置里的界面参数对第一个分组不生效。

### ISSUE THREAD

**Issue by mx4994** [25H/Maya#166]
版本：1.2.7、1.2.8
问题：设置显示两行名称，除了第一个分组不生效，其余分组都会生效；还有显示类型、图标大小也对第一个分组不生效。
第一个分组：
![image](https://user-images.githubusercontent.com/52325833/147628457-76a02117-9de6-40ff-a1a5-809dcd8a1863.png)
第二个分组：
![image](https://user-images.githubusercontent.com/52325833/147628507-b5a39bd2-5e69-473a-acb2-9f46a4b43b73.png)

**Comment by 25H** [comment]
分类处右键设置，这个优先级高于全局设置

**Comment by mx4994** [comment]
确实是这样，都忘记了分组的设置。
