### ISSUE TITLE
UWP应用是否有办法可以添加

### ISSUE THREAD

**Issue by xct99** [25H/Maya#17]
感谢开发！如题，在微软商店下载的UWP应用，如日历、计算器、设置等其他软件，是否有办法添加到快速启动面板呢？试了下，拖不过去

**Comment by 25H** [comment]
目前没这方面计划

**Comment by up-up-star** [comment]
嗯，目前可以把应用从开始菜单，先拖到桌面上创建快捷方式（其他位置也行），然后再把这个快捷方式添加进去就行了
