### ISSUE TITLE
Windows 找不到 ....\Maye.exe 

### ISSUE THREAD

**Issue by looeyWei** [25H/Maya#170]
从github下载.zip 文件，然后解压，然后点击Maye.exe文件，弹出一个警告框“Windows 找不到 Maye.exe”

![image](https://user-images.githubusercontent.com/45961441/150681225-217d2d2b-fae1-4710-a64b-f5910bed6298.png)

**Comment by 7peanuts** [comment]
被你的杀毒软件删掉了，去杀软里还原并添加信任
