### ISSUE TITLE
maye添加的程序不能显示正确的缩略图，重建图标缓存也不行

### ISSUE THREAD

**Issue by 1332186865** [25H/Maya#175]
<img width="343" alt="捕获" src="https://user-images.githubusercontent.com/90539564/156477649-cd7ffffa-4c85-4667-b877-e275f59b3bbd.PNG">
就是这个样子，我也不知道哪里出了问题

**Comment by 25H** [comment]
右键编辑，我看看路径

**Comment by 1332186865** [comment]
<img width="288" alt="1" src="https://user-images.githubusercontent.com/90539564/157042997-6709e11c-ef3b-4022-9edf-87d092a7e0af.PNG">
<img width="434" alt="2" src="https://user-images.githubusercontent.com/90539564/157043002-eba966ae-b497-48cf-9a38-8493261df1cc.PNG">
第一个的设置是这样的
<img width="286" alt="3" src="https://user-images.githubusercontent.com/90539564/157043006-1f45d324-7804-4370-aa30-07817876f542.PNG">
微信的设置
我以为是空格的原因，这个就加上了引号，结果提示文件未找到，图标变成了这样，重建缓存也不行
<img width="240" alt="5" src="https://user-images.githubusercontent.com/90539564/157043352-85a4d946-8f8f-433c-bec5-3f5837598df1.PNG">
再把目标和起始位置的引号去掉
<img width="294" alt="6" src="https://user-images.githubusercontent.com/90539564/157043563-d1f92a70-3d8c-4b98-b003-dd3b7a863a43.PNG">
图标就显示正常了？！
<img width="320" alt="7" src="https://user-images.githubusercontent.com/90539564/157043776-9969d982-2522-477c-9107-1d4c6bfe4056.PNG">
现在是这样

**Comment by 25H** [comment]
你这路径明显不对，还有个检查下图标指向路径

**Comment by 25H** [comment]
如果不会改就直接将文件或快捷方式拖进来

**Comment by 1332186865** [comment]
好的好的，谢谢大佬指点
