### ISSUE TITLE
繁體中文測試結果

### ISSUE THREAD

**Issue by cmhdream** [25H/Maya#18]
軟體本身 設定介面 沒有支援 繁體中文
看到的是亂碼

01. 使用 locale Emulator 將介面翻譯簡體中文
    可以執行 檢視簡體中文 但是會造成無法拖拉捷徑進去主介面

02. 介面色彩主題，因為簡體關係 可以設定
    但是程式關閉後 在開啟 設定會無法運作 又回來白色介面
    後來我把 skin 資料夾裡面的檔案名稱 改成繁體中文檔名 就可以解決
![Maya 扢离_201206_](https://user-images.githubusercontent.com/24859526/101268610-039f5200-37a0-11eb-814e-f80c390ce535.jpg)
![Maya_201206_](https://user-images.githubusercontent.com/24859526/101268611-04d07f00-37a0-11eb-86fe-d3774b198ddd.jpg)

**Comment by 25H** [comment]
目前暂不打算做多语言支持😊

**Comment by cmhdream** [comment]
收到，感謝.

Andy

25H <notifications@github.com> 於 2020年12月6日 週日 上午11:57寫道：

**Comment by miaomiaosoft** [comment]
乱码的问题其实你可以参考这里
https://www.zhihu.com/question/34761050

**Comment by cmhdream** [comment]
Hi,

     感謝您得資訊.. 謝謝..

Andy

miao_miao <notifications@github.com> 於 2020年12月15日 週二 上午3:34寫道：
