### ISSUE TITLE
【建议】滚轮切换分组优化

### ISSUE THREAD

**Issue by banzhiz** [25H/Maya#182]
![image](https://user-images.githubusercontent.com/77912560/162639037-9e400ea7-5a39-4b3b-8821-1b5f0ff00fbe.png)
目前滚轮切换分组有效范围仅仅在标签分组内，希望支持在整个标签显示区域范围内滚轮切换；
或者判断当前分组是否需要滚动，若否则全局滚轮切换分组（这样可以让用户无脑切换分组，不用再增加注意力到移动鼠标至标签栏上）

**Comment by 25H** [comment]
maye lite已实现
