### ISSUE TITLE
操作友好性建议

### ISSUE THREAD

**Issue by luowue** [25H/Maya#19]
1. 在点开搜索时，希望能点击面板内空白处进行取消搜索，比重新点击上方的搜索图标更快捷。
2. 当设置面板最小化到任务栏时，无法通过主面板菜单选项中点击设置打开，希望改进。

**Comment by 25H** [comment]
1) 搜索目前支持ESC按键关闭。
2) 可以具体说下吗，最小化托盘时无法通过托盘右键菜单的 "显示/隐藏" 打开主窗口吗？

**Comment by luowue** [comment]
我的意思是无法通过点击主面板（下图所示位置）来打开被最小化在任务栏的设置面板。

![屏幕截图 2020-12-06 121253](https://user-images.githubusercontent.com/55343657/101271292-8a622800-37bc-11eb-9cc1-b58e1d8287fc.png)

![QQ图片20201206122419](https://user-images.githubusercontent.com/55343657/101271475-fdb86980-37bd-11eb-9464-845c6e5a0d45.png)

**Comment by 25H** [comment]
感谢提供建议，😊
