### ISSUE TITLE
建议增加搜索功能

### ISSUE THREAD

**Issue by Briy09** [25H/Maya#2]
1. 建议增加搜索功能。
2. 参考CLaunch的属性设置，在“编辑”对话框中增加“始终以最小化/最大化运行”、“热键”、“更改图标”等。
3. 贴到屏幕边缘时自动隐藏。
4. 可修改主窗口标题，比如“aiyamaya”
5. 双击新建分类，双击某一个分类重命名。
6. https://github.com/25H/Maya/issues/1 中的分类1中的项目，用鼠标移动到分类2中，希望能自动添加到分类2

**Comment by 25H** [comment]
感谢提供建议😊
