### ISSUE TITLE
请问怎么取消边缘吸附

### ISSUE THREAD

**Issue by xivi1839** [25H/Maya#210]
请问怎么取消边缘吸附，只要一移动到桌面屏幕边缘放开鼠标直接吸附到屏幕边缘，我想取消这个，想穿过，就像记事本一样，随便移动随便放，不用吸附边缘的那种效果

**Comment by 25H** [comment]
这个不是吸附，maye目前禁止移出屏幕外，为来可能会加入相关选项

**Comment by xivi1839** [comment]
太好了，感谢
