### ISSUE TITLE
边缘吸附问题

### ISSUE THREAD

**Issue by PaulHerrero** [25H/Maya#27]
开启边缘吸附后，鼠标距离边缘还有一大段距离就被调出

**Comment by 25H** [comment]
dpi多少？分辨率？几个屏幕？

**Comment by PaulHerrero** [comment]
![image](https://user-images.githubusercontent.com/56058332/102587545-f773a700-4146-11eb-9110-c9dab0083945.png)
缩放100%

**Comment by 25H** [comment]
鼠标没到边缘窗口就弹出来了？

**Comment by PaulHerrero** [comment]
对。有时把鼠标放到边缘会反复弹出收起

**Comment by 25H** [comment]
试下1.1.2版本，看看有没有这个问题

**Comment by cmhdream** [comment]
1.1.1 ＆ 1.1.2 會造成 其它軟體 移到有網頁連結的位址上方 滑鼠一直閃 原本軟體有提示 都無法顯示出來

**Comment by PaulHerrero** [comment]
1.1.2 鼠标移动到桌面边缘有时会导致 maya 疯狂闪现，

**Comment by 25H** [comment]
> 1.1.1 ＆ 1.1.2 會造成 其它軟體 移到有網頁連結的位址上方 滑鼠一直閃 原本軟體有提示 都無法顯示出來
> 後來測試之前的版本也有此問題

chrome firefox edge 浏览器测试没问题，你用的是哪个？

**Comment by 25H** [comment]
> 会导致 maya 疯狂闪现，

软件设置那里都开了什么，我测试下

**Comment by cmhdream** [comment]
是某軟體內的一個網路連結，但不只這個軟體,
包括 rebelle 4 的適用版本，我繪畫就會一直彈出適用購買窗口。

我把 maya 關閉就好了。

![Snipaste_2020-12-18_21-03-28](https://user-images.githubusercontent.com/24859526/102617837-bd20fe80-4174-11eb-82de-0fb305324ad4.jpg)

**Comment by cmhdream** [comment]
我的設置，還有我的系統環境是繁體中文


[cfg.zip](https://github.com/25H/Maya/files/5715837/cfg.zip)

**Comment by PaulHerrero** [comment]
![Snipaste_2020-12-19_08-49-28](https://user-images.githubusercontent.com/56058332/102676194-57199300-41d7-11eb-8119-f38af8dfae74.png)
![Snipaste_2020-12-19_08-49-42](https://user-images.githubusercontent.com/56058332/102676197-5a148380-41d7-11eb-844a-b79f380a2bb1.png)
![Snipaste_2020-12-19_08-49-52](https://user-images.githubusercontent.com/56058332/102676198-5aad1a00-41d7-11eb-9c03-e0d6a59b6602.png)
![Snipaste_2020-12-19_08-50-06](https://user-images.githubusercontent.com/56058332/102676200-5bde4700-41d7-11eb-8fbe-292640eb14a5.png)
![Snipaste_2020-12-19_08-50-15](https://user-images.githubusercontent.com/56058332/102676201-5c76dd80-41d7-11eb-86b8-6678b935ce37.png)

**Comment by 25H** [comment]
> 是某軟體內的一個網路連結，當滑鼠移到上方，就會一直閃爍，
> 不只這個軟體,包括 rebelle 4 的demo版本，我繪畫時每畫一筆，就會一直彈出購買窗口。
> 
> 我把 maya 關閉就好了，這些問題都沒了。
> 
> ![Snipaste_2020-12-18_21-03-28](https://user-images.githubusercontent.com/24859526/102617837-bd20fe80-4174-11eb-82de-0fb305324ad4.jpg)

出现问题的软件发一下，我测试下

**Comment by 25H** [comment]
> 导致 maya 疯狂闪

失焦隐藏引起的问题，已经修复了，等下个版本。

**Comment by cmhdream** [comment]
軟體這邊下載
https://mega.nz/file/pkAG3BbZ#-y5gLre2Lzt8cqeWAZiuKPLLb4rzZqjBk11H1-9GNRw

**Comment by 25H** [comment]
> 軟體這邊下載
> https://mega.nz/file/pkAG3BbZ#-y5gLre2Lzt8cqeWAZiuKPLLb4rzZqjBk11H1-9GNRw

测试没出现你说的问题

**Comment by cmhdream** [comment]
那應該是 繁體中文系統才會有這樣子的問題－我放入 cfg.ini 上面位置就有這樣子的問題

**Comment by 25H** [comment]
>  2020-12-19_15-40-21_0001.mp4 
> 那應該是 繁體中文系統才會有這樣子的問題－我放入 cfg.ini 上面位置就有這樣子的問題

我这复现不了，找不到是那里的问题。。
