### ISSUE TITLE
Maya无法跟随系统缩放问题

### ISSUE THREAD

**Issue by miaor123** [25H/Maya#29]
系统缩放设置后，资源管理器重启了Maya就无法用快捷键呼出并且用菜单栏呼出后没有跟随系统缩放

**Comment by 25H** [comment]
Maya 目前仅支持设置窗口自动缩放，主窗口仅支持首次启动自动缩放，可以根据实际使用情况手动调整“界面->主窗口缩放比”

**Comment by miaor123** [comment]
> Maya当前仅支持设置窗口自动缩放，主窗口仅支持首次启动自动缩放，可以根据实际使用情况手动调整“界面->主窗口缩放比例”

好的 还有一个问题就是Maya在我使用AE时可能重启资源管理器了吧 就屏幕黑了一下回来后无法用快捷键唤出只能重启Maya程序

**Comment by 25H** [comment]
测试重启资源管理器不会影响快捷键功能，目前快捷键功能正在优化可以等下个版本在看看有没有你说的那个问题

**Comment by miaor123** [comment]
> 测试重启资源管理器不会影响快捷键功能，现有快捷键功能正在优化可以等下个版本在看看有没有你说的那个问题

好的 有劳作者大大了

**Comment by miaor123** [comment]
> 测试重启资源管理器不会影响快捷键功能，现有快捷键功能正在优化可以等下个版本在看看有没有你说的那个问题

我突然想到会不会是跟AE冲突了？

**Comment by 25H** [comment]
> > 测试重启资源管理器不会影响快捷键功能，现有快捷键功能正在优化可以等下个版本在看看有没有你说的那个问题
> 
> 我突然想到会不会是跟AE冲突了？

可以检查下定义的快捷键是不是与其他软件冲突了

**Comment by miaor123** [comment]
> > > 测试重启资源管理器不会影响快捷键功能，现有快捷键功能正在优化可以等下个版本在看看有没有你说的那个问题
> > 
> > 
> > 我突然想到会不会是跟AE冲突了？
> 
> 可以检查下定义的快捷键是不是与其他软件冲突了

我看了下不是快捷键冲突具体也不知道原因，就是有时候AE用着可能占用过多会自动清理突然黑屏一下又恢复，之后就唤不出Maya了

**Comment by 25H** [comment]
鼠标中键有这问题吗

**Comment by miaor123** [comment]
我没用鼠标中键打开过。。
