### ISSUE TITLE
分类输入中文为乱码

### ISSUE THREAD

**Issue by xef6273** [25H/Maya#3]
点击分类名称进行编辑时，输入中文，会变成乱码

**Comment by 25H** [comment]
使用环境是什么？什么系统？系统语言中文还是其他？什么输入法？

**Comment by xef6273** [comment]
Win10 X64 专业版 19041.572 
输入法为 谷歌输入法，比较老的一个输入法了

**Comment by 25H** [comment]
> Win10 X64 专业版 19041.572
> 输入法为 谷歌输入法，比较老的一个输入法了

测试没出现乱码的问题，换win10自带的输入法试试。
