### ISSUE TITLE
360为何会鉴定为包含木马

### ISSUE THREAD

**Issue by wmjgh** [25H/Maya#33]
![image](https://user-images.githubusercontent.com/52828616/103046989-0e8e1b00-45c5-11eb-8d6d-e024d0b32640.png)
![image](https://user-images.githubusercontent.com/52828616/103047029-2c5b8000-45c5-11eb-9028-68bc157d3592.png)
![image](https://user-images.githubusercontent.com/52828616/103048291-0e901a00-45c9-11eb-8023-9fee1f926325.png)

是什么原因导致误判了吗

**Comment by Archsuper** [comment]
+1我的也是，报木马了

**Comment by lycleg** [comment]
+1

**Comment by 25H** [comment]
跟外壳编写语言有关，可以忽略
