### ISSUE TITLE
关闭屏幕边缘吸附的问题

### ISSUE THREAD

**Issue by linmii** [25H/Maya#41]
目前Maya的贴边吸附只能在屏幕的四个边上，能否像Rolan一样吸附在四个角上？只有当鼠标移动到角上的时候，才显示主窗口

**Comment by 25H** [comment]
不打算加这个，可以开贴边吸附将窗口移到对应位置实现

**Comment by linmii** [comment]
> 不打算加这个，可以开贴边吸附将窗口移到对应位置实现

标题打错了，是“关于”。

我开启了贴边吸附，但是吸附只能在四个边上，我现在是放在左上角的，但是实际是吸附在屏幕上边的，窗口宽度大约占有屏幕宽度的1/3(12.3寸屏)，鼠标稍微移到左上一点窗口就显示出来了

**Comment by 25H** [comment]
目前有提供键盘/鼠标快捷键
