### ISSUE TITLE
CPU占用80%是什么情况？

### ISSUE THREAD

**Issue by ohahay** [25H/Maya#43]
Maya1.1.3  
CPU i3-9100
maya打开后CPU占用82%左右，
占用太高了

**Comment by ohahay** [comment]
隐藏 不隐藏
CPU占用都非常高

**Comment by 25H** [comment]
这个是1.1.3鼠标类快捷键的bug，

**Comment by Chloe-pro** [comment]
一样。希望能更新一下呢。

**Comment by 25H** [comment]
> 一样。希望能更新一下呢。

可以暂时关闭鼠标类快捷键，1.1.4会修复这个bug

**Comment by Chloe-pro** [comment]
> > 一样。希望能更新一下呢。
> 
> 可以暂时关闭鼠标类快捷键，1.1.4会修复这个bug

ok,关了之后明显好多了，只有5%的占用率了
