### ISSUE TITLE
在系统设置了unicode后, 托盘右键菜单变成乱码了.

### ISSUE THREAD

**Issue by rsyqvthv** [25H/Maya#46]
<img width="101" alt="screenshot_20201226_120548" src="https://user-images.githubusercontent.com/2230369/103151100-e6dcb580-4772-11eb-834e-471ca1db1069.png">

不知道什么原因?

**Comment by 25H** [comment]
目前不支持unicode

**Comment by rsyqvthv** [comment]
> 目前不支持unicode

嗯. 希望今后能有支持. 目前先凑活用吧, 分组尽量使用英文名称.

哦, 对了, 考虑有个英文界面选项吗? 是不是英文界面就会避免这个问题?

**Comment by 25H** [comment]
暂时不考虑做多语言

**Comment by rsyqvthv** [comment]
> 暂时不考虑做多语言

感谢你的及时回复, 避免我有太多奢望.

^_^
