### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xivi1839** [25H/Maya#47]
可以增加导出和导入配置吗，文件名格式最好是：Maya_202012270302（年月日时分秒）
比如电脑重装系统之后，可以把之前备份的导出配置文件，再重新导入就可以继续使用了

**Comment by xivi1839** [comment]
建议点击关闭按钮，能不能不要关闭托盘图标，直接就是缩小到托盘里，如果要退出软件可以直接托盘图标右键退出就可以了呀

**Comment by 25H** [comment]
关闭按钮可以设置隐藏，在 设置>动作>点击关闭按钮时隐藏
项目数据在`JDB.json`，自己注意备份就可以了

**Comment by leosam2048** [comment]
感觉在软件目录增加bak文件夹，按时或者按改动备份一下配置，备份保留一定时间吧。
这样可以万一编辑出问题了，还能回滚回来。
以前自己用rolan，经常会编辑后，感觉不满意，想回滚，回滚不了了。

**Comment by xivi1839** [comment]
大神能不能增加个设置呀，就是点击软件运行后，启动器自动隐藏到托盘里

**Comment by 25H** [comment]
> 大神能不能增加个设置呀，就是点击软件运行后，启动器自动隐藏到托盘里

* 设置>常规>启动时在后台运行
* 设置>动作>隐藏>点击关闭按钮时隐藏

**Comment by xivi1839** [comment]
不行呀，我按照你的设置也一样显示主窗口
![_20201129071150](https://user-images.githubusercontent.com/24610024/103280188-bc0c8e80-4a0a-11eb-920b-bd27400d116c.png)
![_20201229071207](https://user-images.githubusercontent.com/24610024/103280191-bd3dbb80-4a0a-11eb-9991-e26d072a4be8.png)
![88](https://user-images.githubusercontent.com/24610024/103280195-bf077f00-4a0a-11eb-8595-76377f298606.gif)

**Comment by xivi1839** [comment]
有些设置文字应该改一下，有时候设置文字看不懂。
比如：
【点击关闭按钮时隐藏】改成【点击关闭按钮时隐藏主窗口】
