### ISSUE TITLE
问题反馈1227

### ISSUE THREAD

**Issue by xivi1839** [25H/Maya#48]
重命名不支持中文，输入中文变乱码，怎么回事呀
![1111](https://user-images.githubusercontent.com/24610024/103158600-5ea1f300-47fa-11eb-8e31-97775ecb387d.gif)
![_20201327041334](https://user-images.githubusercontent.com/24610024/103158602-619ce380-47fa-11eb-96b2-dacd791fbd1a.png)

**Comment by xivi1839** [comment]
还有快捷键不支持组合键设定

**Comment by xivi1839** [comment]
问题3：缩小之后为什么会出现莫名其妙的自动退出软件呀，托盘图标消失了

**Comment by 25H** [comment]
乱码方面可以参考置顶，
组合键在不冲突的情况下才会生效
关闭按钮可以设置隐藏，在 设置>动作>点击关闭按钮时隐藏

**Comment by xivi1839** [comment]
"乱码方面可以参考置顶"，请问在哪里呀，我没找到，求指路

**Comment by 25H** [comment]
> "乱码方面可以参考置顶"，请问在哪里呀，我没找到，求指路

目前可参考：
![QQ图片20201225140514](https://user-images.githubusercontent.com/36186834/103122196-475bec00-46ba-11eb-8e04-ccfb06fbe27c.png)

此问题会尽快解决

**Comment by xivi1839** [comment]
我还是等你更新版本吧，懒得设置了

**Comment by xivi1839** [comment]
按你的设置操作，还重启电脑，还更新了Maya的最新版本，还是没解决分类重命名中文显示乱码的问题
![_20215701095742](https://user-images.githubusercontent.com/24610024/103439958-b8803e00-4c7c-11eb-9bec-1a221257b624.png)

**Comment by xivi1839** [comment]
![88123](https://user-images.githubusercontent.com/24610024/103440002-0d23b900-4c7d-11eb-9ef6-a450d3c28ccd.gif)

**Comment by 25H** [comment]
升级到1.1.4

**Comment by xivi1839** [comment]
已经升级了，还是一样，你看图上的版本

**Comment by xivi1839** [comment]
取消勾选还是一样

**Comment by xivi1839** [comment]
我安装Rolan都没这个问题，用Maya存在这个问题
![_20212201102257](https://user-images.githubusercontent.com/24610024/103440389-f6329600-4c7f-11eb-9fb9-0e1ae13effaf.png)

**Comment by xivi1839** [comment]
![ludashi](https://user-images.githubusercontent.com/24610024/103440411-1bbf9f80-4c80-11eb-8c81-9a8f6e2725c0.jpg)

**Comment by 25H** [comment]
输入法时什么 我测试下

**Comment by xivi1839** [comment]
我用的是搜狗输入法
