### ISSUE TITLE
建议：批量移动、图标间距自定义

### ISSUE THREAD

**Issue by mx4994** [25H/Maya#52]
1、批量移动。第一次使用，在添加软件分类的时候，只能一个一个的拖动分类，不能批量移动，虽然只是第一次需要这样，但还是希望添加批量移动的支持。
2、图标间距自定义，默认的三种图标模式，除了大图标模式，其余两种间距过小，显示的软件名字只能显示三四个字，看起来也不太美观，大图标模式，图标又太大了，所以希望支持图标间距自定义。

**Comment by 25H** [comment]
批量操作暂不考虑添加
