### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by IUswift** [25H/Maya#53]
您好，我在使用的maya时候被我隐藏了，然后就会存在后台误杀情况，目前windows10用的是火绒和 wise care365。是不是被wise care 清理了？

**Comment by 25H** [comment]
添加下信任就好了，目前因编写语言关系没办法解决误报的问题

**Comment by xivi1839** [comment]
我也是WIN10，也用火绒，没被误杀呀

**Comment by IUswift** [comment]
偶尔会有，现在还好

xivi1839 <notifications@github.com> 于2020年12月29日周二 下午7:27写道：
