### ISSUE TITLE
搜索功能不好用

### ISSUE THREAD

**Issue by Bunnyk001** [25H/Maya#59]
搜索功能不好用
比如搜狗输入法
打字后，回车，字幕上屏，直接打开第1个软件
而第1个软件未必是我想要打开的

当然了，
英文状态下，
会自动让你选择打开哪个软件
没有问题
中文状态下打出来的字，敲回车后就会产生问题

**Comment by 25H** [comment]
感谢提供建议，1.1.4版已解决此问题
