### ISSUE TITLE
希望适配高分辨率屏幕

### ISSUE THREAD

**Issue by mxy493** [25H/Maya#60]
希望能适配高分屏，我的笔记本是2k屏，软件界面很小，字体也小，体验较差。

我个人是Rolan的忠实用户，不过其实只用了它的快捷启动的功能，希望保持桌面整洁

**Comment by 25H** [comment]
目前主窗口仅支持首次启动自动调节缩放比，如果字体小可以到 "设置>界面>窗口与布局>主窗口缩放比"  进行手动调节

**Comment by mxy493** [comment]
> 目前主窗口仅支持首次启动自动调节缩放比，如果字体小可以到 "设置>界面>窗口与布局>主窗口缩放比" 进行手动调节

找到缩放比的设置了，对主界面是有效的，设置界面无变化，如图
<img width="675" alt="Snipaste_2021-01-02_13-22-46" src="https://user-images.githubusercontent.com/46776216/103451330-a1356500-4cfd-11eb-99db-62b23a97a360.png">

**Comment by 25H** [comment]
设置界面未缩放是因1.1.4版dpi获取有点问题，下个版本会修复

**Comment by mxy493** [comment]
> 设置界面未缩放是因1.1.4版dpi获取有点问题，下个版本会修复

好的，感谢开源👍
