### ISSUE TITLE
开机无法自动启动，快捷键无法弹出界面

### ISSUE THREAD

**Issue by Adoubf** [25H/Maya#64]
没有杀毒软件，优先级已设为最高，进程也没有禁止开机自启，但就是无法开机自启。快捷键弹出界面，时灵时不灵，就感觉很奇怪

**Comment by 25H** [comment]
开机启动检查下`C:\Users\***\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 文件夹内是否存在maya快捷方式

快捷键那个是全屏勿扰引起的，可以暂时关闭全屏勿扰，下个版本会修复
