### ISSUE TITLE
bug反馈，和qq图片查看有抵触

### ISSUE THREAD

**Issue by cutebabyzhi** [25H/Maya#65]
此软件开启贴边悬浮后，qq查看图片时候**无法单击图片查看器关闭图片查看器**
不知道这二者是如何发生联系的，望开发者排查修复。

**Comment by 25H** [comment]
qq里的图片查看？测试没问题啊。

**Comment by cutebabyzhi** [comment]
> qq里的图片查看？测试没问题啊。

有，我这里在窗口贴边吸附后，qq查看图片的时候单击图片框，关不掉了
