### ISSUE TITLE
开启自动更新检测后，一直没有自动更新

### ISSUE THREAD

**Issue by Chloe-pro** [25H/Maya#66]
用的是1.1.3的版本，想更新1.1.4版本。不想再重新下新版本，重新设置了。求问

**Comment by 25H** [comment]
这个功能只是检测有没有新版，不包含自动更新，更新新版需要自行下载新版压缩包覆盖，注意`JDB.json`与`cfg.ini`文件就可以了，新版压缩包一般不包含这两个文件

**Comment by Chloe-pro** [comment]
可以了，谢谢啊

**Comment by Chloe-pro** [comment]
回复真快啊

**Comment by Chloe-pro** [comment]
哦哦，可以了。谢谢啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "25H"<notifications@github.com&gt;; 
发送时间: 2021年1月8日(星期五) 晚上6:09
收件人: "25H/Maya"<Maya@noreply.github.com&gt;; 
抄送: "Crawford"<1847867933@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [25H/Maya] 开启自动更新检测后，一直没有自动更新 (#66)





 
这个功能只是检测有没有新版，不包含自动更新，更新新版需要自行下载新版压缩包覆盖，注意JDB.json与cfg.ini文件就可以了，新版压缩包一般不包含这两个文件
