### ISSUE TITLE
能加个软件自动更新吗？

### ISSUE THREAD

**Issue by wuzhumeng** [25H/Maya#67]
如题，每次更新都不知道，希望加个软件自动更新功能。

**Comment by 25H** [comment]
目前又周期3天的新版检测

**Comment by wuzhumeng** [comment]
我都检测不到，打开软件一点提示也没有，还是从423down知道更新的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "25H/Maya"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上7:14
收件人:&nbsp;"25H/Maya"<Maya@noreply.github.com&gt;;
抄送:&nbsp;"立刻"<wuzhumeng@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [25H/Maya] 能加个软件自动更新吗？ (#67)





 
目前又周期3天的新版检测

**Comment by 25H** [comment]
q群里有更新通知
