### ISSUE TITLE
图标显示异常

### ISSUE THREAD

**Issue by catsimple** [25H/Maya#69]
一些图标如adobe全家桶和IDM
被裁剪掉了一部分
![QQ截图20210112223559](https://user-images.githubusercontent.com/23014926/104328442-c52b4e80-5526-11eb-9eef-30469c8b6b58.jpg)
![QQ截图20210112223626](https://user-images.githubusercontent.com/23014926/104328445-c65c7b80-5526-11eb-9efc-c03a1199b9c8.jpg)

**Comment by 25H** [comment]
![2021-01-13_00-12-00](https://user-images.githubusercontent.com/36186834/104340801-070ec180-5534-11eb-9279-7d4c617ad3bb.png)
