### ISSUE TITLE
这里可以移动吗

### ISSUE THREAD

**Issue by xivi1839** [25H/Maya#70]
比如名字有点长的情况下，这里能移动吗
![_20211013021031](https://user-images.githubusercontent.com/24610024/104354748-a5a31e80-5544-11eb-8a77-9623b9531972.png)
![_20211213021244](https://user-images.githubusercontent.com/24610024/104354873-d5522680-5544-11eb-8b7f-c73fdc170960.png)

**Comment by 25H** [comment]
![2021-01-13_13-31-48](https://user-images.githubusercontent.com/36186834/104410657-cb134500-55a3-11eb-8259-57a2edc38217.png)
![2021-01-13_13-32-34](https://user-images.githubusercontent.com/36186834/104410672-d0708f80-55a3-11eb-9b07-cff70e7f83b2.png)

**Comment by xivi1839** [comment]
可以考虑改进成用鼠标移动吗，手动输入太死板了，不够灵活

**Comment by 25H** [comment]
非常用项，没必要
