### ISSUE TITLE
建议：图标间距和一些其他建议

### ISSUE THREAD

**Issue by BiuZero** [25H/Maya#72]
1.希望dalao可以增加图标间距自定义，或者优化一下大图标下的图标间距，2K分辨率下感觉标准和小图标都太小了，用大图标感觉正好，就是间距太大了
2.有快捷方式的同一行，右键无法弹出菜单
3.快捷键显示貌似和停靠边缘吸附有冲突，期望的状态是快捷键唤出后停留，鼠标移到主窗口上面移出后再自动吸附
![QQ截图20210113234142](https://user-images.githubusercontent.com/15268027/104474574-0c145500-55b6-11eb-985f-1e0af4dba628.png)

**Comment by 25H** [comment]
- 2K图标小，可以调整“主窗口缩放比”来实现放大，
- “有快捷方式的同一行” 具体是什么意思？
- 快捷键跟吸附这个问题会尽快修复

**Comment by BiuZero** [comment]
- 大佬，图标间距感觉真的有点过于宽松了，标准图标调整缩放比120左右后效果貌似和直接选大图标差不多🤣，不是说图标小，是间距过大
- “有快捷方式的同一行”具体就是图片这里红色框起来的这个区域，不能右键，要在这个图标下一行才能右键
 [![saaTED.png](https://s3.ax1x.com/2021/01/14/saaTED.png)](https://imgchr.com/i/saaTED)

**Comment by 25H** [comment]
1. 图标间距可以尝试使用不显示项目名，或自己修改下css
2. 菜单这个我会尽快测试下
