### ISSUE TITLE
希望可以隐藏到角落，以及隐藏分类栏的进度条

### ISSUE THREAD

**Issue by mxy493** [25H/Maya#73]
1. 希望可以隐藏窗口到角落，我个人的使用习惯是隐藏到左上角，之前用Rolan，鼠标移到左上角会有一个向右下方展开的效果，觉得挺不错的；
2. 分类栏希望隐藏进度条，分类一般不会太多，保持简洁；
3. 当前1.1.6版分类栏会多占用一个分类的高度，比如我设置8个分类，如果我把窗口高度调整为刚好8个分类的高度，则会有进度条还可以往下滑一个分类的高度，如图：
<img width="299" alt="Snipaste_2021-01-15_21-00-22" src="https://user-images.githubusercontent.com/46776216/104732876-ceabf500-5778-11eb-8fa3-c1cdaaa0306f.png">

**Comment by 25H** [comment]
1. 支持四角隐藏，设置里有选项
2. 暂不打算隐藏
3. 下边距会尽快调整

**Comment by mxy493** [comment]
@25H 你说的是“停靠屏幕四角时吸附”的设置吗？我现在遇到的问题是，开启这个后窗口隐藏，鼠标移到角落窗口不会弹出，只能用快捷键来调出窗口

**Comment by 25H** [comment]
> @25H 你说的是“停靠屏幕四角时吸附”的设置吗？我现在遇到的问题是，开启这个后窗口隐藏，鼠标移到角落窗口不会弹出，只能用快捷键来调出窗口

需要先将窗口移动到某个角才会生效

**Comment by mxy493** [comment]
> > @25H 你说的是“停靠屏幕四角时吸附”的设置吗？我现在遇到的问题是，开启这个后窗口隐藏，鼠标移到角落窗口不会弹出，只能用快捷键来调出窗口
> 
> 需要先将窗口移动到某个角才会生效

确实是放在左上角的，鼠标移出自动隐藏，但鼠标移到角落没法唤出窗口，目前只能用快捷键
![image](https://user-images.githubusercontent.com/46776216/104808215-aaefba00-581f-11eb-89e8-fef6f2060590.png)

**Comment by 25H** [comment]
cfg.ini 传一份，我测试下

**Comment by mxy493** [comment]
> cfg.ini 传一份，我测试下

[cfg.zip](https://github.com/25H/Maya/files/5824516/cfg.zip)

**Comment by 25H** [comment]
测试没问题，具体是怎么触发的？

**Comment by mxy493** [comment]
@25H 你看下我录的动图吧，操作就是拖到左上角自动隐藏，但鼠标移到左上角不能唤出窗口，隐藏后就只能用快捷键唤出了
![tmp](https://user-images.githubusercontent.com/46776216/104820535-5163ab80-5870-11eb-9112-2dae43c5baa8.gif)

**Comment by 25H** [comment]
其他三个角落也会这样吗

**Comment by mxy493** [comment]
> 其他三个角落也会这样吗

都是这样的

**Comment by 25H** [comment]
> > 其他三个角落也会这样吗
> 
> 都是这样的

贴边吸附会出现无法唤醒的问题吗

**Comment by mxy493** [comment]
@25H 刚测试了，开启“停靠屏幕四角时吸附”的情况下贴边也没法唤出；关闭“停靠屏幕四角时吸附”并开启“停靠屏幕边缘时吸附”，贴边可以正常唤出
