### ISSUE TITLE
多屏幕吸附时，放到副屏中的Maya会跳回主屏，并且抽搐

### ISSUE THREAD

**Issue by CNJackyYe** [25H/Maya#76]
使用环境WIN10

**Comment by CNJackyYe** [comment]
![两屏幕演示](https://user-images.githubusercontent.com/32700242/105259182-44272380-5bc6-11eb-9a8b-c706680a9061.gif)

**Comment by CNJackyYe** [comment]
还挺有节奏的

**Comment by 25H** [comment]
目前不支持多屏
