### ISSUE TITLE
出来新版本软件后，需要重新安装软件吗？无法把之前的旧版本直接升成新版本吗？

### ISSUE THREAD

**Issue by zhuxiaowei0924** [25H/Maya#78]
出来新版本软件后，如果需要重新安装软件，再重新把各个快捷方式重新导入，比较麻烦；可不可以直接把之前的旧版本升成新版本，而之前已经列好的快捷方式而不受影响？

**Comment by 25H** [comment]
新版本解压后直接覆盖旧版就可以了
