### ISSUE TITLE
建议添加窗口到屏幕四角隐藏，鼠标靠近呼出

### ISSUE THREAD

**Issue by Ding-Vic** [25H/Maya#8]
刚刚试用下，很不错！
我很喜欢的一点是用alt-tab切换程序时不会在里面显示；在此基础上建议添加窗口到屏幕四角隐藏，鼠标靠近呼出。

**Comment by 25H** [comment]
alt+tab 不显示是因为用的隐藏而非最小化，四角隐藏可以用“主窗口停靠屏幕边缘时吸附”

**Comment by 821064597** [comment]
> 
> 
> alt+tab 不显示是因为用的隐藏而非最小化，四角隐藏可以用“主窗口停靠屏幕边缘时吸附”代替。

停靠边缘的话触发区域偏大，如果是屏幕四个角只有一个点触发，不容易误触。当然如果太麻烦就不用了哈

**Comment by 25H** [comment]
> > alt+tab 不显示是因为用的隐藏而非最小化，四角隐藏可以用“主窗口停靠屏幕边缘时吸附”代替。
> 
> 停靠边缘的话触发区域偏大，如果是屏幕四个角只有一个点触发，不容易误触。当然如果太麻烦就不用了哈

这功能暂不考虑开发，后期需求较大可能会考虑开发😊

**Comment by 821064597** [comment]
> 
> 
> > > alt+tab 不显示是因为用的隐藏而非最小化，四角隐藏可以用“主窗口停靠屏幕边缘时吸附”代替。
> > 
> > 
> > 停靠边缘的话触发区域偏大，如果是屏幕四个角只有一个点触发，不容易误触。当然如果太麻烦就不用了哈
> 
> 这功能暂不考虑开发，后期需求较大可能会考虑开发😊

**Comment by Lx-0374** [comment]
1、可以添加拖动分类标签进行排序的功能吗
2、可以添加对不同分类设置不同列表显示类型的功能吗

**Comment by 25H** [comment]
> 可以添加拖动分类标签进行排序的功能吗

1) 分类拖动排序一直支持，之前一些版本可能因bug导致无法拖动，不过1.0.7已经修复了
2) 不同分类显示不同类型这项功能以后可能会添加。
