### ISSUE TITLE
Maya 1.17和1.1.8版本隐藏窗口后自动显示的问题

### ISSUE THREAD

**Issue by slaris** [25H/Maya#80]
在Maya 1.1.6版本中还没有这个问题，但在升级到Maya 1.1.7和1.1.8后，只要鼠标经过隐藏窗口所在区域就会自动弹出。查看了设置信息，好像没有类似的设置啊。

**Comment by 25H** [comment]
看看是不是开了“贴边吸附”/“四角吸附”
