### ISSUE TITLE
在1.1.8版本的标签中输入中文，显示的是乱码？

### ISSUE THREAD

**Issue by zhuxiaowei0924** [25H/Maya#85]
在1.1.8版本的标签中输入中文，显示的是乱码；但在另一台电脑上输入中文则显示正常，比较奇怪，是什么问题？

**Comment by 25H** [comment]
这个是之前别人给的方法。 这个问题我会尽快解决

---
![QQ图片20210209135518](https://user-images.githubusercontent.com/36186834/107321955-7bf6fc00-6ade-11eb-99ea-5c26264c717e.png)
![QQ图片20210209135525](https://user-images.githubusercontent.com/36186834/107321961-7dc0bf80-6ade-11eb-8377-e333e12cfae8.png)
美式键盘删掉就好了
