### ISSUE TITLE
觸發時間可否設定 或停駐一秒鐘後才觸發

### ISSUE THREAD

**Issue by cmhdream** [25H/Maya#86]
因為視窗觸發 很容易誤觸 雖然動畫跑得挺順
但是放在哪邊都是個 很容易觸發的區域

可否像火絨防毒一樣 有個顯示小圖示 停留一秒鐘才出現視窗 

![0tH1il2Ttl](https://user-images.githubusercontent.com/24859526/107438388-5bc14e80-6b6b-11eb-8d67-b11c695a220b.gif)

**Comment by 25H** [comment]
好，有空我会改一下

**Comment by cmhdream** [comment]
1.1.9 有設置，但是 鼠标悬停托盘图标(显示) 測試過 好像沒有作用

**Comment by cmhdream** [comment]
1.1.9 測試結果
![su2ecpHtQT](https://user-images.githubusercontent.com/24859526/107614279-f95c7100-6c84-11eb-84fb-fe67bab8fc57.gif)

**Comment by 25H** [comment]
119没有加入延时

**Comment by cmhdream** [comment]
有延遲設定阿
![MayaSetting02-11_222820](https://user-images.githubusercontent.com/24859526/107649526-82d96680-6cb8-11eb-8439-1cb327bf55c2.png)

**Comment by 25H** [comment]
这个延迟是值鼠标悬停在托盘时的延时，判断方式是鼠标悬停且在延迟过程中未移动过鼠标
