### ISSUE TITLE
为啥360报警，viruscan.org上也有告警

### ISSUE THREAD

**Issue by zminthan** [25H/Maya#89]
软件用起来真的很顺手，很方便，但是为啥杀软告警，用起来慌慌的…………

**Comment by 25H** [comment]
编写语言的问题，maya除了开机启动以外不会动maya目录以外的东西

**Comment by zminthan** [comment]
大神新年快乐呀 大过年了都在线 佩服佩服 您的软件编写得真好 此类软件用过不下五六款 maya最轻量最高效简洁 真希望哪天能来源 我好好学习一下 冒昧问下maya是什么语言写的？

**Comment by zminthan** [comment]
使用时候有个小问题 就是我平时都设置启动程序定位在鼠标位置，平时在主屏时正常响应，但是当我把鼠标挪到副屏幕时候，启动时就不能显示在副屏幕了 大神有时间可以改进下 不胜感谢

**Comment by xivi1839** [comment]
360卸载了吧，推荐安装火绒

**Comment by aiqinxuancai** [comment]
因为是易语言写的

**Comment by 25H** [comment]
> 使用时候有个小问题 就是我平时都设置启动程序定位在鼠标位置，平时在主屏时正常响应，但是当我把鼠标挪到副屏幕时候，启动时就不能显示在副屏幕了 大神有时间可以改进下 不胜感谢

-
