### ISSUE TITLE
图标缓存bug

### ISSUE THREAD

**Issue by Bronya-Rayi** [25H/Maya#90]
有的图标缓存会重复
这是第一个栏目的图标
![image](https://user-images.githubusercontent.com/47048823/107899441-34a6ba80-6f79-11eb-8cb2-c67e2d4580ee.png)
这是第二个
![image](https://user-images.githubusercontent.com/47048823/107899454-412b1300-6f79-11eb-92fa-ae0df63acc68.png)
重建当前栏目缓存后可以看到，第二个应该是这样的
![image](https://user-images.githubusercontent.com/47048823/107899482-599b2d80-6f79-11eb-9728-8b5f145cf19c.png)
但是，一旦第二个栏目重建了缓存，第一个栏目就会变化成第二个栏目的图标
![image](https://user-images.githubusercontent.com/47048823/107899515-72a3de80-6f79-11eb-98c2-a4ac6e020e24.png)

**Comment by 25H** [comment]
内存缓存吗？

**Comment by Bronya-Rayi** [comment]
不是，图标的缓存
![image](https://user-images.githubusercontent.com/47048823/107903857-442c0080-6f85-11eb-9286-5f84ea038dce.png)

**Comment by 25H** [comment]
1.1.9？我这测不出来阿

**Comment by Bronya-Rayi** [comment]
![1](https://user-images.githubusercontent.com/47048823/107904194-054a7a80-6f86-11eb-9a17-5871929d6100.gif)

**Comment by Bronya-Rayi** [comment]
1.19，我看了下配置文件，不知道为啥有两个编号一样的项目，估计问题出在这了
![image](https://user-images.githubusercontent.com/47048823/107904324-7722c400-6f86-11eb-88b4-c0974a5955f0.png)
![image](https://user-images.githubusercontent.com/47048823/107904332-7a1db480-6f86-11eb-995b-98134cc702c0.png)

**Comment by 25H** [comment]
好 我有空看下入库那里，你暂时可以手动改下重复的id

**Comment by 25H** [comment]
注意编码格式

**Comment by Bronya-Rayi** [comment]
好的，大佬辛苦，启动器很好用的

**Comment by Bronya-Rayi** [comment]
大佬应该是我手贱改配置文件弄得，我又新开了个虚拟机试了下，软件没问题

**Comment by 25H** [comment]
https://github.com/25H/Maya/blob/main/JDB.json.js
