### ISSUE TITLE
win10弹出UAC权限提示后，Maya的UI会从侧面出来

### ISSUE THREAD

**Issue by aiqinxuancai** [25H/Maya#95]
如题，本来缩在边上的界面会弹出，鼠标移动上去再移开才会回去

**Comment by 25H** [comment]
我这没测出来，你那都开什么了？

**Comment by aiqinxuancai** [comment]
> 我这没测出来，你那都开什么了？

缩到左上角，然后用Win+L锁屏后解锁可触发，窗口会自动出来，然后要鼠标移动上去一下。

**Comment by aiqinxuancai** [comment]
似乎最新的版本并未解决，每次锁屏解锁后界面都会自动被弹出
![QQ图片20210318170454](https://user-images.githubusercontent.com/4475018/111600168-164c0d00-880c-11eb-8ca3-1bf5b95736f1.gif)

**Comment by 25H** [comment]
锁屏之前忘记测试了

**Comment by aiqinxuancai** [comment]
1.2.3测试还是可以复现....我就不录屏了

**Comment by 25H** [comment]
我这开贴边测着没问题了啊，

**Comment by aiqinxuancai** [comment]
> 我这开贴边测着没问题了啊， 有空我在试试

我是缩左上角的，你试试看

**Comment by 25H** [comment]
> > 我这开贴边测着没问题了啊， 有空我在试试
> 
> 我是缩左上角的，你试试看

找到问题了，一个api忘做判断了🤣
