### ISSUE TITLE
开启全屏勿扰后依然会弹出Maya

### ISSUE THREAD

**Issue by OP027-Air** [25H/Maya#97]
浏览器全屏时鼠标经过屏幕边缘依然会弹出Maya，勾选了全屏免打扰和停靠边缘时吸附，另外有时鼠标移出maya界面时maya依然存在，不会消失。
版本：1.19，浏览器：Edge 88.0.705.74(64位)，系统：1909，18363.1379

**Comment by 25H** [comment]
Edge 测试没问题，具体是怎么触发的？

**Comment by cmhdream** [comment]
我也是一樣的 我還以為是因為我再繁體中文環境才會這樣子
這就是我希望 能超過一秒或兩秒鐘 才出現

**Comment by OP027-Air** [comment]
> Edge 测试没问题，具体是怎么触发的？



> Edge 测试没问题，具体是怎么触发的？

大体是我开启了全屏勿扰设置，并把maya吸附在左边屏幕边缘，正常情况下当鼠标没有经过时maya是隐藏的，经过后才会显示，当我使用edge这类全屏程序时，鼠标经过屏幕边缘，maya依然会弹出来，仿佛全屏勿扰这个设置没有起到任何作用

**Comment by 25H** [comment]
> 会弹出来，仿佛

全屏是指窗口铺满屏幕，而不是最大化可以看见任务栏那种。

ps：edge  F11键的那种
